### ISSUE TITLE
Icons not showing in treeview

### ISSUE THREAD

**Issue by Ernest-Jones** [file-icons/atom#480]
Hi,

Well, icons are not displayed in the treeview anymore...

Happy new year to you and thanks for the package

Baptiste

**Comment by Alhadis** [comment]
More information needed. Are you using Nuclide, or...? Can you attach a screenshot?

**Comment by Ernest-Jones** [comment]
Hi again,

I am using nothing else than atom for Debian...

The icons are normally displayed on the tabs but not in the tree view. I send you a screenshot tomorrow.

Thank you

Baptiste

**Comment by richarddewit** [comment]
I was able to confirm this, but then I removed and reinstalled the package and restarted Atom. This solved the issue for me.

**Comment by Ernest-Jones** [comment]
Ok, great news !

Thank you

Happy new year

Baptiste

**Comment by richarddewit** [comment]
But now, after switching projects, the icons are indeed gone. I can only get them back by reloading Atom.

No errors whatsoever

**Comment by newsch** [comment]
Fixed for me in 2.0.5

**Comment by Ernest-Jones** [comment]
Hi,

The package is working well but it throw an error when atom is starting..

Here is the log :

Might be because I am using Atom 1.11 and not Atom 1.12...

Anyway, just to let you know

Have a nice day


Baptiste

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Debian GNU/Linux
**Thrown From**: [file-icons](https://github.com/file-icons/atom) 
package, v2.0.7


### Stack Trace

Uncaught TypeError: document.styleSheets[Symbol.iterator] is not a function

```
At /home/baptiste/.atom/packages/file-icons/lib/ui.js:113

TypeError: document.styleSheets[Symbol.iterator] is not a function
     at UI.getStyleElement 
(/home/baptiste/.atom/packages/file-icons/lib/ui.js:113:33)
     at UI.getThemeColour 
(/home/baptiste/.atom/packages/file-icons/lib/ui.js:123:27)
     at UI.checkMotif 
(/home/baptiste/.atom/packages/file-icons/lib/ui.js:136:23)
     at Immediate._ [as _onImmediate] 
(/home/baptiste/.atom/packages/file-icons/lib/ui.js:17:27)
     at tryOnImmediate (timers.js:534:15)
     at processImmediate [as _immediateCallback] (timers.js:514:5)
```

### Commands

```
```

### Config

```json
{
   "core": {
     "autoHideMenuBar": true,
     "disabledPackages": [
       "language-sql"
     ],
     "excludeVcsIgnoredPaths": false,
     "ignoredNames": [
       "Default: .hg",
       ".svn",
       ".DS_Store",
       "._*",
       "Thumbs.db"
     ],
     "packagesWithKeymapsDisabled": [],
     "telemetryConsent": "no"
   },
   "file-icons": {
     "strategies": {}
   }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0 (active)
autocomplete, v0.47.0 (inactive)
file-header, v1.13.0 (active)
file-icons, v2.0.7 (active)
fold-functions, v0.4.4 (active)
language-ejs, v0.4.0 (inactive)
language-sql-mysql, v0.3.1 (inactive)
linter, v1.11.18 (active)
linter-jshint, v3.0.2 (active)
platformio-ide-terminal, v2.2.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ryanfox1985** [comment]
Hi, this morning I updated to last version and I have the same problem (I'm using nuclide). I tried to disable/reinstall but doesn't work.

**Comment by tanguydevos** [comment]
Alors baptiste, on parle anglais ?

**Comment by styx** [comment]
And what about Nuclide? Previously this package worked.

**Comment by Alhadis** [comment]
@styx Are you running the latest version of File-Icons? (v2.0.8)

If so, have you restarted Atom?

**Comment by styx** [comment]
@Alhadis heh, I was on 2.0.7 (as there was no update on my morning). Works as expected after update. Thnx.

**Comment by Alhadis** [comment]
Mostly-complete Nuclide support was actually added about an hour ago. There are still limitations, which [I've documented in the release notes](https://github.com/DanBrooker/file-icons/releases/tag/v2.0.8).

**Comment by Alhadis** [comment]
@Ernest-Jones This appears to have been fixed by recent updates, so I'm closing this.

If this happens again, please file a new issue.

**Comment by 73** [comment]
Hi,

I am using Atom 1.55.0 and the wonderful [file-icon](https://atom.io/packages/file-icons) package.
Not so long ago the icons of the tree-view disappeared, still showing the icons in the tabs. 
In order to get the icons displayed again I had to collapse the tree-view and expand is again.
In search for a solution I fount this issue, so I would like to place my solution here for every other that finds this issue.
Going though my packages I found that another package was causing this.
I am documenting what works for me today and what does not:

### TESTED AND CAUSING THE ISSUE
- [dbclick-tree-view](https://atom.io/packages/dbclick-tree-view).
- [atom-tree-view-dblclick](https://atom.io/packages/atom-tree-view-dblclick).
- [double-click-tree-view](https://atom.io/packages/double-click-tree-view)

### THE ONE THAT WORKED
- [tree-view-click](https://atom.io/packages/tree-view-click)

Best regards,
73
