### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeIcon' of null

### ISSUE THREAD

**Issue by markainick** [file-icons/atom#528]
I'm just trying to open a ".log" file. The error is thrown only when opening the file, and not when the file is in view in the treeview.

Report:

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Unknown Windows Version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package   2.0.12

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeIcon' of null

```
At C:\Users\John\.atom\packages\file-icons\lib\service\icon-node.js:31

TypeError: Cannot read property 'onDidChangeIcon' of null
	at new IconNode (C:\Users\John\.atom\packages\file-icons\lib\service\icon-node.js:31:12)
	at new Tab (C:\Users\John\.atom\packages\file-icons\lib\consumers\tab.js:17:19)
	at Tabs.add (C:\Users\John\.atom\packages\file-icons\lib\consumers\tabs.js:70:16)
	at disposables.add.UI.delay.onOpenEditor.editor (C:\Users\John\.atom\packages\file-icons\lib\consumers\tabs.js:36:10)
	at Immediate.setImmediate (C:\Users\John\.atom\packages\file-icons\lib\ui.js:82:40)
	at runCallback (timers.js:574:20)
	at tryOnImmediate (timers.js:554:5)
	at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -0:44.6.0 editor:move-to-beginning-of-word (input.hidden-input)
  3x -0:43.6.0 editor:move-to-end-of-word (input.hidden-input)
     -0:42.9.0 core:move-right (input.hidden-input)
 16x -0:42.4.0 editor:move-to-end-of-word (input.hidden-input)
     -0:39.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:38.2.0 core:move-up (input.hidden-input)
     -0:38.2.0 core:move-right (input.hidden-input)
     -0:37.3.0 core:save (input.hidden-input)
     -0:28.5.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:27.3.0 core:confirm (input.hidden-input)
  9x -0:26.3.0 core:move-down (input.hidden-input)
  7x -0:24.9.0 core:move-left (input.hidden-input)
     -0:23.8.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:23.4.0 core:backspace (input.hidden-input)
     -0:22.2.0 autocomplete-plus:cancel (input.hidden-input)
  2x -0:21.3.0 core:save (input.hidden-input)
```

### Config

```json
{
	"core": {
		"automaticallyUpdate": false,
		"packagesWithKeymapsDisabled": [],
		"telemetryConsent": "no",
		"themes": [
			"one-dark-ui",
			"atom-dark-fusion-syntax"
		]
	},
	"file-icons": {
		"tabPaneIcon": false
	}
}
```

### Installed Packages

```bash
# Active themes
atom-dark-fusion-syntax   2.0.2
one-dark-ui               1.8.2

# Consumer packages
archive-view              0.62.0
find-and-replace          0.204.5
fuzzy-finder              1.4.0
tabs                      0.103.1
tree-view                 0.211.1

# Active packages (Core excluded)
auto-indent               0.5.0
color-picker              2.2.4
ctrl-dir-scroll           0.2.2
docblockr                 0.9.1
file-icons                2.0.12
goto-definition           1.1.19

# Inactive packages
advanced-open-file        0.16.5
```

**Comment by ninoM** [comment]
Experienced this as well. What gives?

**Comment by matheusgrieger** [comment]
Getting it only when collapsing a folder from the sidebar. There is one JS file that is left without icon, even though all others have, and there is nothing special about it.

Exactly the same problem.

**Comment by Alhadis** [comment]
@markainick What version of Windows are you running? Atom's report isn't saying much:

> **System:** Unknown Windows Version

@matheusgrieger Can you include a screenshot, please? Preferably with a stack trace.

**To everybody else:** If you're going to say *"I have this issue too!"*, please, for the love of God, include a stack-trace at the ***barest minimum***.

**Comment by markainick** [comment]
@Alhadis Windows 8.1

**Comment by RoseFlunder** [comment]
I have this issue too on Windows 10.
For me it happens when a new file is created by my code and then this new file pop up ins the navigation tree without an icon and this error,

`[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: DESKTOP-LOEHBQE
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.12


### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeIcon' of null

```
At C:\Users\Stephan\.atom\packages\file-icons\lib\service\icon-node.js:31

TypeError: Cannot read property 'onDidChangeIcon' of null
    at new IconNode (C:\Users\Stephan\.atom\packages\file-icons\lib\service\icon-node.js:31:12)
    at new TreeEntry (C:\Users\Stephan\.atom\packages\file-icons\lib\consumers\tree-entry.js:41:19)
    at TreeView.track (C:\Users\Stephan\.atom\packages\file-icons\lib\consumers\tree-view.js:72:25)
    at resource.onDidFindEntries.entries (C:\Users\Stephan\.atom\packages\file-icons\lib\consumers\tree-view.js:87:64)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TreeEntry.scanEntries (C:\Users\Stephan\.atom\packages\file-icons\lib\consumers\tree-entry.js:122:18)
    at TreeEntry.function.source.onDidAddEntries.disposables.add.source.onDidAddEntries (C:\Users\Stephan\.atom\packages\file-icons\lib\consumers\tree-entry.js:37:62)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:125:28)
    at Directory.module.exports.Directory.reload (C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory.js:370:29)
    at PathWatcher.<anonymous> (C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory.js:233:30)
    at PathWatcher.onChange (C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:143:26)
    at HandleWatcher.<anonymous> (C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:171:30)
    at emitThree (events.js:116:13)
    at HandleWatcher.emit (events.js:194:7)
    at HandleWatcher.onEvent (C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:71:23)
    at C:\Users\Stephan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:20:41
```

### Commands

```
 39x -4:16.3.0 core:backspace (input.hidden-input)
     -4:04.6.0 autocomplete-plus:confirm (input.hidden-input)
     -4:01.9.0 editor:newline (input.hidden-input)
  2x -3:43.2.0 core:move-right (input.hidden-input)
     -3:34.7.0 editor:newline (input.hidden-input)
     -3:33.2.0 autocomplete-plus:confirm (input.hidden-input)
     -3:30.9.0 core:move-right (input.hidden-input)
     -3:29.5.0 core:backspace (input.hidden-input)
     -3:21.9.0 core:delete (input.hidden-input)
     -3:20.9.0 core:move-down (input.hidden-input)
  2x -3:20.5.0 core:move-right (input.hidden-input)
  6x -3:19.9.0 core:select-right (input.hidden-input)
     -3:17.7.0 core:select-left (input.hidden-input)
  2x -3:15 core:save (input.hidden-input)
  2x -1:21.4.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".pioenvs",
      ".piolibdeps",
      ".clang_complete",
      ".gcc-flags.json"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (active)
file-icons, v2.0.12 (active)
language-ini, v1.17.0 (active)
linter, v1.11.21 (active)
linter-eslint, v8.0.0 (active)
react, v0.16.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

`

**Comment by matheusgrieger** [comment]
@Alhadis my bad!

Got the error again, here is everything:

1. Collapsed a folder in sidebar
2. Deleted a file
3. Created a new folder through Windows Explorer
  Error thrown, folder without icon

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Windows 10 64 bit
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.12


### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeIcon' of null

```
At C:\Users\mathe\.atom\packages\file-icons\lib\service\icon-node.js:31

TypeError: Cannot read property 'onDidChangeIcon' of null
    at new IconNode (C:\Users\mathe\.atom\packages\file-icons\lib\service\icon-node.js:31:12)
    at new TreeEntry (C:\Users\mathe\.atom\packages\file-icons\lib\consumers\tree-entry.js:41:19)
    at TreeView.track (C:\Users\mathe\.atom\packages\file-icons\lib\consumers\tree-view.js:72:25)
    at resource.onDidFindEntries.entries (C:\Users\mathe\.atom\packages\file-icons\lib\consumers\tree-view.js:87:64)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TreeEntry.scanEntries (C:\Users\mathe\.atom\packages\file-icons\lib\consumers\tree-entry.js:122:18)
    at TreeEntry.function.source.onDidAddEntries.disposables.add.source.onDidAddEntries (C:\Users\mathe\.atom\packages\file-icons\lib\consumers\tree-entry.js:37:62)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:125:28)
    at Directory.module.exports.Directory.reload (C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory.js:370:29)
    at PathWatcher.<anonymous> (C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory.js:233:30)
    at PathWatcher.onChange (C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:143:26)
    at HandleWatcher.<anonymous> (C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:152:30)
    at emitThree (events.js:116:13)
    at HandleWatcher.emit (events.js:194:7)
    at HandleWatcher.onEvent (C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:71:23)
    at C:\Users\mathe\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:20:41
```

### Commands

```
     -1:22.8.0 editor:newline (input.hidden-input)
     -1:22.5.0 snippets:previous-tab-stop (input.hidden-input)
     -1:22.5.0 editor:outdent-selected-rows (input.hidden-input)
     -1:22.2.0 core:paste (input.hidden-input)
     -1:21 pane:show-next-recently-used-item (input.hidden-input)
     -1:20.9.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -1:20 pane:show-next-recently-used-item (input.hidden-input)
     -1:19.8.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -1:18.4.0 core:save (input.hidden-input)
     -0:43.1.0 docblockr:parse-enter (input.hidden-input)
     -0:43.1.0 editor:newline (input.hidden-input)
     -0:39.5.0 core:save (input.hidden-input)
     -0:39.1.0 core:close (input.hidden-input)
     -0:25.3.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:21.1.0 core:backspace (input.hidden-input)
     -0:20.8.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.3 (active)
aligner-css, v1.2.0 (active)
aligner-javascript, v1.0.0 (active)
atom-alignment, v0.12.1 (active)
atom-beautify, v0.29.16 (active)
atom-material-syntax, v1.0.2 (active)
atom-material-syntax-dark, v0.2.7 (inactive)
atom-material-ui, v1.3.9 (active)
color-picker, v2.2.4 (active)
docblockr, v0.9.1 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.12 (active)
highlight-selected, v0.12.0 (active)
language-lua, v0.9.11 (active)
language-pug, v0.0.19 (active)
minimap, v4.26.7 (active)
minimap-cursorline, v0.2.0 (active)
minimap-highlight-selected, v4.5.0 (active)
nord-atom-syntax, v0.6.0 (inactive)
nord-atom-ui, v0.10.0 (inactive)
pigments, v0.39.0 (active)
preview, v0.17.0 (inactive)
project-manager, v3.3.3 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Maelstromeous** [comment]
Confirmed I'm getting this also. It seems when new files are generated (e.g. a log file that you've just cleared) it doesn't know what to do with it.

The result is that the new file has no icon.

Stack trace:

```
TypeError: Cannot read property 'onDidChangeIcon' of null
    at new IconNode (C:\Users\admin\.atom\packages\file-icons\lib\service\icon-node.js:31:12)
    at new TreeEntry (C:\Users\admin\.atom\packages\file-icons\lib\consumers\tree-entry.js:41:19)
    at TreeView.track (C:\Users\admin\.atom\packages\file-icons\lib\consumers\tree-view.js:72:25)
    at resource.onDidFindEntries.entries (C:\Users\admin\.atom\packages\file-icons\lib\consumers\tree-view.js:87:64)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TreeEntry.scanEntries (C:\Users\admin\.atom\packages\file-icons\lib\consumers\tree-entry.js:122:18)
    at TreeEntry.function.source.onDidAddEntries.disposables.add.source.onDidAddEntries (C:\Users\admin\.atom\packages\file-icons\lib\consumers\tree-entry.js:37:62)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:125:28)
    at Directory.module.exports.Directory.reload (C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory.js:370:29)
    at PathWatcher.<anonymous> (C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\tree-view\lib\directory.js:233:30)
    at PathWatcher.onChange (C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:143:26)
    at HandleWatcher.<anonymous> (C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:171:30)
    at emitThree (events.js:116:13)
    at HandleWatcher.emit (events.js:194:7)
    at HandleWatcher.onEvent (C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:71:23)
    at C:\Users\admin\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\pathwatcher\lib\main.js:20:41
```

**Comment by Maelstromeous** [comment]
This exception also triggers when you close and reopen the folder which contains the newly created file.

**Comment by Alhadis** [comment]
Can people please pull the latest changes from master and confirm if 7242e5ab has solved this?

I couldn't reproduce the issue even on Windows (??!), but I strongly suspect it's related to path separators... 😠

```bash
cd /some/temp/path
git clone https://github.com/file-icons/atom.git file-icons
cd file-icons
apm install . && apm link -d .
```

Then restart Atom in dev mode.

**Comment by Alhadis** [comment]
... or just install the latest patch and tell me if things are still fucked. 👍 

Can't actually confirm if this issue's been resolved or not, so I've left it open. Feedback, please.

This means from you guys.

**Comment by ninoM** [comment]
Just installed the latest patch 2.0.13 using Atom 1.13.0 running on Windows 10. Problem is fixed on my end. No more annoying pop-ups! Thank you @Alhadis .. Will provide a better bug report next time.

**Comment by MarcoNiemann** [comment]
Have patch 2.0.13 using Atom 1.13.1 and I am still getting the error message:

![image](https://cloud.githubusercontent.com/assets/9252676/22390167/c3d037c8-e4e9-11e6-9a84-0d8aaeb9c463.png)

The stacktrace looks as follows:

```
TypeError: Cannot read property 'onDidChangeIcon' of null
    at new IconNode (C:\Users\Marco\.atom\packages\file-icons\lib\service\icon-node.js:31:12)
    at new Tab (C:\Users\Marco\.atom\packages\file-icons\lib\consumers\tab.js:17:19)
    at Tabs.add (C:\Users\Marco\.atom\packages\file-icons\lib\consumers\tabs.js:70:16)
    at disposables.add.UI.delay.onOpenEditor.editor (C:\Users\Marco\.atom\packages\file-icons\lib\consumers\tabs.js:36:10)
    at Immediate.setImmediate (C:\Users\Marco\.atom\packages\file-icons\lib\ui.js:82:40)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by Alhadis** [comment]
@MarcoNiemann Have you actually restarted Atom?

**Comment by MarcoNiemann** [comment]
@Alhadis Yep, restarted it several times. Also uninstalled `file-icons` and reinstalled it to ensure nothing went wrong with the update. 

Interestingly my side-bar at the moment lacks all icons, while the tabs still have the respective icons in front of the file names. I actually get the error messages when I am searching for files via `CMD + P`.

**Comment by gitvon** [comment]
**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Unknown Windows Version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package, v2.0.13


### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeIcon' of null

```
At C:\Users\Von Zuben\.atom\packages\file-icons\lib\service\icon-node.js:31

TypeError: Cannot read property 'onDidChangeIcon' of null
    at new IconNode (C:\Users\Von Zuben\.atom\packages\file-icons\lib\service\icon-node.js:31:12)
    at new Tab (C:\Users\Von Zuben\.atom\packages\file-icons\lib\consumers\tab.js:17:19)
    at Tabs.add (C:\Users\Von Zuben\.atom\packages\file-icons\lib\consumers\tabs.js:70:16)
    at disposables.add.UI.delay.onOpenEditor.editor (C:\Users\Von Zuben\.atom\packages\file-icons\lib\consumers\tabs.js:36:10)
    at Immediate.setImmediate (C:\Users\Von Zuben\.atom\packages\file-icons\lib\ui.js:82:40)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

**Comment by gitvon** [comment]
When  drag the file to another folder and create a file

**Comment by OvermindDL1** [comment]
Just got this error, never had it before, Windows 10, same stack traces as above, only file without an icon is a .json file that contains json, but I've not touched that file since yesterday...

**Comment by Alhadis** [comment]
Think I figured out what was wrong. Some of the consumer classes were still using unnormalised path separators, which means we still had combinations of `C:\this\` and `C:/this/` floating around. I've fixed it, but I still haven't found a way to reproduce the original error... so I can't be 100% confident this *has* solved the issue.

**Comment by otakusid** [comment]
I have this issue on win 10, when I switch between branches in my VCS, while atom opened in VCS root directory

**Comment by Alhadis** [comment]
I'm finishing up a new release, but I'm taking a moment to add something that'll make it a hell of a lot easier on you guys to provide helpful stat-reports.

Which will be needed if these issues are still occurring, because they damn well better be fixed by `2.0.14`. ;p

**Comment by Alhadis** [comment]
@MarcoNiemann, @gitvon, @otakusid Are you still having issues after installing `v2.0.14`...?

**Comment by Keyhaku** [comment]
Hello,

I'm using Atom 1.3.1 with file-icons 2.0.14 on Win 7 (64 bits) and having  the same issue

```
TypeError: Cannot read property 'onDidChangeIcon' of null
    at new IconNode (D:\Users\<USERNAME>\.atom\packages\file-icons\lib\service\icon-node.js:31:12)
    at new TreeEntry (D:\Users\<USERNAME>\.atom\packages\file-icons\lib\consumers\tree-entry.js:41:19)
    at TreeView.track (D:\Users\<USERNAME>\.atom\packages\file-icons\lib\consumers\tree-view.js:72:25)
    at resource.onDidFindEntries.entries (D:\Users\<USERNAME>\.atom\packages\file-icons\lib\consumers\tree-view.js:87:64)
    at Function.module.exports.Emitter.simpleDispatch (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TreeEntry.scanEntries (D:\Users\<USERNAME>\.atom\packages\file-icons\lib\consumers\tree-entry.js:122:18)
    at TreeEntry.function.source.onDidAddEntries.disposables.add.source.onDidAddEntries (D:\Users\<USERNAME>\.atom\packages\file-icons\lib\consumers\tree-entry.js:37:62)
    at Function.module.exports.Emitter.simpleDispatch (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:125:28)
    at Directory.module.exports.Directory.reload (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\tree-view\lib\directory.js:370:29)
    at Directory.module.exports.Directory.expand (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\tree-view\lib\directory.js:383:12)
    at tree-view-directory.DirectoryView.expand (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\tree-view\lib\directory-view.js:179:24)
    at tree-view-directory.DirectoryView.toggleExpansion (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\tree-view\lib\directory-view.js:166:21)
    at TreeView.module.exports.TreeView.entryClicked (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\tree-view\lib\tree-view.js:472:15)
    at tree-view-directory.<anonymous> (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\tree-view\lib\tree-view.js:190:26)
    at space-pen-div.dispatch (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (D:\Users\<USERNAME>\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

**Comment by Alhadis** [comment]
@Keyhaku What were you doing just before this occurred?

**Comment by Keyhaku** [comment]
I'm currently learning python 3, so I was creating a script, using the json module and the fonction json.dump to create the file username.json and fill it automatically.

The first time the script created this file, no problem.

Just after I destoyed the json file,  and rerunned the script the problem occured.

**Comment by Alhadis** [comment]
@Keyhaku Please let me know if this still happens after updating to [v2.0.15](https://github.com/file-icons/atom/releases/tag/v2.0.15). Thank you.

**Comment by Keyhaku** [comment]
Hello,

As of 2.0.15 the problem is corrected. Thank you

**Comment by Alhadis** [comment]
Perfect.

Gonna mark this as resolved. If anybody has any problems, **please** file a new issue. It'll make everybody's life easier.
